void ARROW_ELLIPTIC(float ELLIPSE_REZIRADIUSX,float ELLIPSE_REZIRADIUSY,float ELLIPSE_STARTX,float ELLIPSE_STARTY,float &A,float &B,float &C,float &D,float &E)
{
	ELLIPSE_REZIRADIUSX*=ELLIPSE_REZIRADIUSX;
	ELLIPSE_REZIRADIUSY*=ELLIPSE_REZIRADIUSY;
	D=+4*ELLIPSE_STARTX*ELLIPSE_REZIRADIUSX-4*ELLIPSE_STARTX*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY-4*ELLIPSE_STARTX*ELLIPSE_REZIRADIUSY*ELLIPSE_REZIRADIUSX-4*ELLIPSE_STARTX*ELLIPSE_STARTX*ELLIPSE_STARTX*fsqr(ELLIPSE_REZIRADIUSX);
	C=+4*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY)+2*ELLIPSE_REZIRADIUSY-2*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY)-2*fsqr(ELLIPSE_REZIRADIUSY)-2*fsqr(ELLIPSE_STARTX)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+4*fsqr(ELLIPSE_STARTX)*fsqr(ELLIPSE_REZIRADIUSX)-2*ELLIPSE_REZIRADIUSX+2*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSY*ELLIPSE_REZIRADIUSX+2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+2*fsqr(ELLIPSE_STARTX)*fsqr(ELLIPSE_REZIRADIUSX);
	B=+4*ELLIPSE_STARTX*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY-4*ELLIPSE_STARTX*fsqr(ELLIPSE_REZIRADIUSX);
	A=+fsqr(ELLIPSE_REZIRADIUSY)-2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+fsqr(ELLIPSE_REZIRADIUSX);
	E=+fsqr(fsqr(ELLIPSE_STARTX))*fsqr(ELLIPSE_REZIRADIUSX)+2*fsqr(ELLIPSE_STARTX)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+2*fsqr(ELLIPSE_STARTX)*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY-2*fsqr(ELLIPSE_STARTX)*ELLIPSE_REZIRADIUSX+1*fsqr(ELLIPSE_REZIRADIUSY)+2*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY)-2*ELLIPSE_REZIRADIUSY+fsqr(fsqr(ELLIPSE_STARTY))*fsqr(ELLIPSE_REZIRADIUSY)-2*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSY+1-4*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY);
}
//√(1²-x²)=a√(1-b(x-o√(1-cx²))²)
//1²-x²=a²-a²b(x-o√(1-cx²))²
//1²-x²=a²-a²b(x²-2ox√(1-cx²)+o²(1-cx²))
//1²-x²=a²-a²b(x²-2ox√(1-cx²)+o²-cx²o²)
//1²-x²=a²-a²bx²+2a²box√(1-cx²)-a²bo²+a²bcx²o²
//1²-x²-a²+a²bx²+a²bo²-a²bcx²o²=2a²box√(1-cx²)
//(1²-x²-a²+a²bx²+a²bo²-a²bcx²o²)²=4a⁴b²o²x²(1-cx²)

//1-2x²-2a²+2a²bx²+2a²bo²-2a²bcx²o²+
//x⁴+2x²a²-2a²bx⁴-2x²a²bo²+2a²bcx⁴o²+
//a⁴-2a⁴bx²-2a⁴bo²+2a⁴bcx²o²+
//+a⁴b²x⁴+2a⁴b²x²o²-2a⁴b²cx⁴o²+
//a⁴b²o⁴-2a⁴b²cx²o⁴+
//a⁴b²c²x⁴o⁴
//-4a⁴b²o²x²+4a⁴b²cx⁴o²

float NORMALIZEELLIPSE(double ELLIPSE_REZIRADIUSX,double ELLIPSE_RADIUSY,double SHEAR)
{
	double RA; double RB;
	ELLIPSE_RADIUSY*=ELLIPSE_RADIUSY;
	SHEAR*=SHEAR;
double A=1-2*ELLIPSE_RADIUSY*ELLIPSE_REZIRADIUSX+fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)+2*ELLIPSE_RADIUSY*ELLIPSE_REZIRADIUSX*SHEAR-2*fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)*SHEAR+4*fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)*SHEAR+fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)*fsqr(SHEAR);
double B=-2+2*ELLIPSE_RADIUSY*ELLIPSE_REZIRADIUSX+2*ELLIPSE_RADIUSY-2*ELLIPSE_RADIUSY*ELLIPSE_REZIRADIUSX*SHEAR-2*fsqr(ELLIPSE_RADIUSY)*ELLIPSE_REZIRADIUSX+2*fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)*SHEAR-4*fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)*SHEAR+2*fsqr(ELLIPSE_RADIUSY)*ELLIPSE_REZIRADIUSX*SHEAR-2*fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)*fsqr(SHEAR)-2*ELLIPSE_RADIUSY*ELLIPSE_REZIRADIUSX*SHEAR;
double C=+1-2*ELLIPSE_RADIUSY+2*ELLIPSE_RADIUSY*ELLIPSE_REZIRADIUSX*SHEAR+fsqr(ELLIPSE_RADIUSY)-2*fsqr(ELLIPSE_RADIUSY)*ELLIPSE_REZIRADIUSX*SHEAR+fsqr(ELLIPSE_RADIUSY)*fsqr(ELLIPSE_REZIRADIUSX)*fsqr(SHEAR);
RA=(-B+sqrt((B*B)-(4*A*C)))/(2*A);
RB=(-B-sqrt((B*B)-(4*A*C)))/(2*A);
RA=sqrt(fabs(RA));
RB=sqrt(fabs(RB));
if (RA>RB) return RB; else return RA;
}
