void ARROW_ELLIPTIC(float ELLIPSE_REZIRADIUSX,float ELLIPSE_REZIRADIUSY,float ELLIPSE_STARTX,float ELLIPSE_STARTY,float &A,float &B,float &C,float &D,float &E)
{
	ELLIPSE_REZIRADIUSX*=ELLIPSE_REZIRADIUSX;
	ELLIPSE_REZIRADIUSY*=ELLIPSE_REZIRADIUSY;
	D=+4*ELLIPSE_STARTX*ELLIPSE_REZIRADIUSX-4*ELLIPSE_STARTX*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY-4*ELLIPSE_STARTX*ELLIPSE_REZIRADIUSY*ELLIPSE_REZIRADIUSX-4*ELLIPSE_STARTX*ELLIPSE_STARTX*ELLIPSE_STARTX*fsqr(ELLIPSE_REZIRADIUSX);
	C=+4*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY)+2*ELLIPSE_REZIRADIUSY-2*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY)-2*fsqr(ELLIPSE_REZIRADIUSY)-2*fsqr(ELLIPSE_STARTX)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+4*fsqr(ELLIPSE_STARTX)*fsqr(ELLIPSE_REZIRADIUSX)-2*ELLIPSE_REZIRADIUSX+2*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSY*ELLIPSE_REZIRADIUSX+2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+2*fsqr(ELLIPSE_STARTX)*fsqr(ELLIPSE_REZIRADIUSX);
	B=+4*ELLIPSE_STARTX*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY-4*ELLIPSE_STARTX*fsqr(ELLIPSE_REZIRADIUSX);
	A=+fsqr(ELLIPSE_REZIRADIUSY)-2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+fsqr(ELLIPSE_REZIRADIUSX);
	E=+fsqr(fsqr(ELLIPSE_STARTX))*fsqr(ELLIPSE_REZIRADIUSX)+2*fsqr(ELLIPSE_STARTX)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+2*fsqr(ELLIPSE_STARTX)*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY-2*fsqr(ELLIPSE_STARTX)*ELLIPSE_REZIRADIUSX+1*fsqr(ELLIPSE_REZIRADIUSY)+2*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY)-2*ELLIPSE_REZIRADIUSY+fsqr(fsqr(ELLIPSE_STARTY))*fsqr(ELLIPSE_REZIRADIUSY)-2*fsqr(ELLIPSE_STARTY)*ELLIPSE_REZIRADIUSY+1-4*fsqr(ELLIPSE_STARTY)*fsqr(ELLIPSE_REZIRADIUSY);
}
//√(1²-x²)=a√(1-b(x-o√(1-cx²)))
//1²-x²=a²-a²b²(x-o√(1-cx²))²
//1²-x²=a²-a²b²(x²-2ox√(1-cx²)+o²(1-cx²))
//1²-x²=a²-a²b²(x²-2ox√(1-cx²)+o²-cx²o²)
//1²-x²=a²-a²b²x²+2a²b²ox√(1-cx²)-a²b²o²+a²b²cx²o²
//1²-x²-a²+a²b²x²+a²b²o²-a²b²cx²o²=2a²b²ox√(1-cx²)
//(1²-x²-a²+a²b²x²+a²b²o²-a²b²cx²o²)²=4a⁴b⁴o²x²(1-cx²)

//1-2x²-2a²+2a²b²x²+2a²b²o²-2a²b²cx²o²+
//x⁴+2x²a²-2a²b²x⁴-2x²a²b²o²+2a²b²cx⁴o²+
//a⁴-2a⁴b²x²-2a⁴b²o²+2a⁴b²cx²o²+
//+a⁴b⁴x⁴+2a⁴b⁴x²o²-2a⁴b⁴cx⁴o²+
//a⁴b⁴o⁴-2a⁴b⁴cx²o⁴+
//a⁴b⁴c²x⁴o⁴
//-4a⁴b⁴o²x²+4a⁴b⁴cx⁴o²

void NORMALIZEELLIPSE(float ELLIPSE_REZIRADIUSX,float ELLIPSE_REZIRADIUSY,float ELLIPSE_STARTX,float ELLIPSE_STARTY,float &A,float &B,float &C,float &D,float &E)
{
	ELLIPSE_REZIRADIUSX*=ELLIPSE_REZIRADIUSX;
	ELLIPSE_REZIRADIUSY*=ELLIPSE_REZIRADIUSY;
A=+-2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)+2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY*SHEAR*sqr(o)-2*sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)*SHEAR*sqr(o)+4*sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)*SHEAR*sqr(o);
B=0;
C=-2+2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY+2*ELLIPSE_REZIRADIUSX-2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY*sqr(o)-2*sqr(ELLIPSE_REZIRADIUSX)*ELLIPSE_REZIRADIUSY+2*sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)*sqr(o)+sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)*sqr(*SHEAR)*sqr(sqr(o))-4*sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)*sqr(o)+2*sqr(ELLIPSE_REZIRADIUSX)*ELLIPSE_REZIRADIUSY*SHEAR*sqr(o)-2*sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)*SHEAR*sqr(sqr(o))-2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY*SHEAR*sqr(o);
D=0;
E=+1-2*ELLIPSE_REZIRADIUSX+2*ELLIPSE_REZIRADIUSX*ELLIPSE_REZIRADIUSY*sqr(o)+sqr(ELLIPSE_REZIRADIUSX)-2*sqr(ELLIPSE_REZIRADIUSX)*ELLIPSE_REZIRADIUSY*sqr(o)+sqr(ELLIPSE_REZIRADIUSX)*sqr(ELLIPSE_REZIRADIUSY)*sqr(sqr(o));
}
